# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
        ('tuners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_url', models.CharField(max_length=300)),
                ('add_timestamp', models.DateTimeField()),
                ('youtube_id', models.CharField(max_length=100, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Car')),
                ('tuner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuners.Tuner')),
            ],
        ),
    ]
