# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170916_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('664415c3-21dc-46fe-bbea-aacb8c0d69ea'), primary_key=True, serialize=False),
        ),
    ]
