# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170919_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('412d9f13-3ec6-48e2-97f8-3d646ca0bcab'), primary_key=True, serialize=False),
        ),
    ]
