# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170919_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b50ccbc6-c37c-470d-b2f3-2ec7ff59aced'), primary_key=True, serialize=False),
        ),
    ]
