# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170919_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5743df9b-5b9e-4548-b482-51bf96f62560'), primary_key=True, serialize=False),
        ),
    ]
