# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170920_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46059be8-c3a5-4062-b3f0-dd32bc9df857'), primary_key=True, serialize=False),
        ),
    ]
