# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('add_timestamp', models.DateTimeField()),
                ('preview_image', models.CharField(max_length=300, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.IntegerField(default=0)),
                ('remote_url', models.CharField(max_length=300)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Build')),
            ],
        ),
        migrations.CreateModel(
            name='BuildThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_url', models.CharField(max_length=300)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Build')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('generation', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
