# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 23:49
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('make', 'model', 'generation'), unique=True, verbose_name='slug'),
        ),
    ]
