# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.Car'),
            preserve_default=False,
        ),
    ]
