# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-11 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_build_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='trim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
