# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20170810_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildmedia',
            name='media_type',
            field=models.CharField(choices=[('0', 'YOUTUBE_VIDEO')], max_length=2),
        ),
    ]
