# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20170810_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildSocialMediaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_account_type', models.CharField(choices=[('I', 'INSTAGRAM')], max_length=2)),
                ('account_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('remote_url', models.URLField(blank=True, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Build')),
            ],
        ),
        migrations.AlterField(
            model_name='buildmedia',
            name='media_type',
            field=models.CharField(choices=[('YT', 'YOUTUBE_VIDEO')], max_length=2),
        ),
        migrations.AlterField(
            model_name='buildmedia',
            name='remote_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
