# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 01:28
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20170810_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from=('name', 'car.make', 'car.model', 'car.trim'), unique=True, verbose_name='slug'),
        ),
    ]
