# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tuners', '0001_initial'),
        ('cars', '0008_build_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='tuner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tuners.Tuner'),
        ),
        migrations.AlterField(
            model_name='build',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='name', unique=True, verbose_name='slug'),
        ),
    ]
