# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuners', '0001_initial'),
        ('cars', '0010_auto_20170813_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='build',
            name='tuner',
        ),
        migrations.AddField(
            model_name='build',
            name='tuners',
            field=models.ManyToManyField(blank=True, null=True, to='tuners.Tuner'),
        ),
    ]
