# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20170813_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildmedia',
            name='external_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
