# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_buildmedia_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildmedia',
            name='preview_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
