# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_buildmedia_preview_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('color_hex', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='purpose',
            field=models.ManyToManyField(to='cars.CarPurpose'),
        ),
    ]
