# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0017_auto_20170817_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildsocialmediaaccount',
            name='build',
        ),
        migrations.RemoveField(
            model_name='buildthread',
            name='build',
        ),
        migrations.AddField(
            model_name='build',
            name='build_thread',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='ig_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='youtube_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BuildSocialMediaAccount',
        ),
        migrations.DeleteModel(
            name='BuildThread',
        ),
    ]
