# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_featuredbuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('ig_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube_channel_link', models.URLField(blank=True, null=True)),
                ('make_and_model', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('build_thread', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
