# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 23:28
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_carsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpurpose',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=100, populate_from='name', verbose_name='slug'),
        ),
    ]
