# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0022_auto_20170828_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='tuners',
            field=models.ManyToManyField(blank=True, to='tuners.Tuner'),
        ),
    ]
