# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0023_auto_20170829_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBulletPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bullet_point', models.CharField(max_length=200)),
                ('order', models.SmallIntegerField(default=0)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.Build')),
            ],
        ),
    ]
