# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0025_auto_20170916_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='has_been_sold',
            field=models.NullBooleanField(default=False),
        ),
    ]
