# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0026_build_has_been_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildmedia',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buildmedia',
            name='featured_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
