# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_auto_20170919_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildmedia',
            name='add_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
